### ISSUE TITLE
Fix `isStolen` text to appear under device name

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/stolen-or-not-app#1]
Fix the `You have reported this device stolen ... ` -text in `user_settings_page.dart` to appear under the device name instead of next to it. Make sure it looks nice in smaller screens. You can test it by going to Settings-page in your emulator and click `Report stolen` button to make the text appear.

**Comment by Aryashakya** [comment]
Hi, I would like to work on this issue.

**Comment by nikohoffren** [comment]
> Hi, I would like to work on this issue.

Sure, go ahead.
